import { useForm, UseFormReturn, UseFormProps } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { IFormSchema } from '../interfaces/form-schema.interface';

/**
 * Custom hook to initialize a form with the builder schema.
 * Wraps react-hook-form's useForm with Zod integration.
 * 
 * @param {IFormSchema} schema - The form schema generated by the builder.
 * @param {UseFormProps} options - Additional options for useForm.
 * @returns {UseFormReturn} The form methods.
 */
export const useFormBuilder = (
  schema: IFormSchema,
  options?: UseFormProps
): UseFormReturn => {
  return useForm({
    resolver: zodResolver(schema.validationSchema),
    ...options,
  });
};
